name: Merge to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-test-release:
    if: github.repository_owner == 'centennial-oss'
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Run clean, test, and build-release
        run: |
          make clean test build-release

