name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    if: github.repository_owner == 'centennial-oss'
    runs-on: macos-14
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Generate build info for CI
        run: |
          COMMIT="${{ github.sha }}" \
          DATE="$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")" \
          CONFIG="Debug" \
          ARCH="arm64" \
          make generate-build-info

      - name: Run clean, test, and build
        run: |
          make clean test build

